# Generated by Django 2.2.6 on 2019-11-12 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='title',
        ),
    ]
