# Generated by Django 2.2.6 on 2019-11-13 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Univercity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='univercity',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='employee.Univercity'),
        ),
    ]
